[workspace]
members = [
    "crates/src-tauri",
    "crates/launcher_core",
    "crates/vcmp_core",
    "crates/library_redirector"
]
resolver = "3"


[profile.dev]
# inherits = "release"  # 在开发时也使用发布优化

[profile.release]
codegen-units = 1
lto = true